// Generated by Orc from sharpjs-countku-wisdom.fs.
// Edit the F# source bank; do not hand-edit this rendered module.
const advisors = [
  {
    "id": "advisor-5-mathematics",
    "persona": "Lantern Geometer",
    "sigil": "∑",
    "category": "advisor-haiku",
    "title": "The patient proof",
    "era": "Euler, number, and proof",
    "lines": [
      "Numbers cross the bridge",
      "A pattern waits to be seen",
      "The curve bends, not truth"
    ],
    "body": "Numbers cross the bridge\nA pattern waits to be seen\nThe curve bends, not truth",
    "unlockAt": 5,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Euler Archive",
    "sourceUrl": "https://eulerarchive.maa.org/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-10-poetry",
    "persona": "Road Poet",
    "sigil": "句",
    "category": "advisor-haiku",
    "title": "The cut and the echo",
    "era": "Bashō and the short form",
    "lines": [
      "Silence counts as form",
      "The cut makes two views converse",
      "Let the pause remain"
    ],
    "body": "Silence counts as form\nThe cut makes two views converse\nLet the pause remain",
    "unlockAt": 10,
    "sourceKind": "countku-haiku",
    "sourceLabel": "The Narrow Road to the Deep North",
    "sourceUrl": "https://en.wikisource.org/wiki/The_Narrow_Road_to_the_Deep_North",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-15-confucius",
    "persona": "Patient Teacher",
    "sigil": "仁",
    "category": "advisor-haiku",
    "title": "Practice and reflection",
    "era": "The Analects",
    "lines": [
      "Learning wakes the mind",
      "A question keeps wisdom near",
      "Walk then look again"
    ],
    "body": "Learning wakes the mind\nA question keeps wisdom near\nWalk then look again",
    "unlockAt": 15,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Analects",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3330",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-20-strategy",
    "persona": "Quiet Strategist",
    "sigil": "策",
    "category": "advisor-haiku",
    "title": "Before the first move",
    "era": "Sun Tzu and deliberate position",
    "lines": [
      "Patience reads the wind",
      "The empty road hides its force",
      "Let the field decide"
    ],
    "body": "Patience reads the wind\nThe empty road hides its force\nLet the field decide",
    "unlockAt": 20,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Art of War",
    "sourceUrl": "https://www.gutenberg.org/ebooks/132",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-25-shinto",
    "persona": "Shrine Archivist",
    "sigil": "祓",
    "category": "advisor-haiku",
    "title": "Renewal at the gate",
    "era": "Shinto ritual and renewal",
    "lines": [
      "Renewal starts small",
      "Still water mirrors the sky",
      "Care makes room for awe"
    ],
    "body": "Renewal starts small\nStill water mirrors the sky\nCare makes room for awe",
    "unlockAt": 25,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Kokugakuin · Encyclopedia of Shinto",
    "sourceUrl": "https://d-museum.kokugakuin.ac.jp/eos/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-30-evolution",
    "persona": "Field Naturalist",
    "sigil": "枝",
    "category": "advisor-haiku",
    "title": "Changes that take root",
    "era": "Darwin and adaptive form",
    "lines": [
      "Small changes take root",
      "The patient years shape the wing",
      "No form stands alone"
    ],
    "body": "Small changes take root\nThe patient years shape the wing\nNo form stands alone",
    "unlockAt": 30,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · On the Origin of Species",
    "sourceUrl": "https://www.gutenberg.org/ebooks/1228",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-35-stoicism",
    "persona": "Porch Philosopher",
    "sigil": "選",
    "category": "advisor-haiku",
    "title": "The next right act",
    "era": "Epictetus and Marcus Aurelius",
    "lines": [
      "Choice lives in the pause",
      "The storm cannot name your mind",
      "The helm stays with you"
    ],
    "body": "Choice lives in the pause\nThe storm cannot name your mind\nThe helm stays with you",
    "unlockAt": 35,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Meditations",
    "sourceUrl": "https://www.gutenberg.org/ebooks/2680",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-40-wasan",
    "persona": "Sangaku Keeper",
    "sigil": "算",
    "category": "advisor-haiku",
    "title": "Proof beneath the eaves",
    "era": "Edo-period Japanese mathematics",
    "lines": [
      "Sangaku keeps watch",
      "Geometry becomes prayer",
      "The temple learns math"
    ],
    "body": "Sangaku keeps watch\nGeometry becomes prayer\nThe temple learns math",
    "unlockAt": 40,
    "sourceKind": "countku-haiku",
    "sourceLabel": "National Diet Library · Japanese Mathematics",
    "sourceUrl": "https://www.ndl.go.jp/math/e/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-45-tao",
    "persona": "Water Listener",
    "sigil": "道",
    "category": "advisor-haiku",
    "title": "The yielding road",
    "era": "The Tao Te Ching",
    "lines": [
      "Stillness holds the wheel",
      "Still centers can turn the wheel",
      "The open hand holds"
    ],
    "body": "Stillness holds the wheel\nStill centers can turn the wheel\nThe open hand holds",
    "unlockAt": 45,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Tao Te Ching",
    "sourceUrl": "https://www.gutenberg.org/ebooks/216",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-50-zen",
    "persona": "Bell Keeper",
    "sigil": "無",
    "category": "advisor-haiku",
    "title": "The room already here",
    "era": "Zen practice and direct attention",
    "lines": [
      "Dust settles by dawn",
      "One clear act outlives the noise",
      "Nothing needs a name"
    ],
    "body": "Dust settles by dawn\nOne clear act outlives the noise\nNothing needs a name",
    "unlockAt": 50,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Sacred Books of the East",
    "sourceUrl": "https://www.sacred-texts.com/bud/zen/index.htm",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-55-psychology",
    "persona": "Habit Cartographer",
    "sigil": "習",
    "category": "advisor-haiku",
    "title": "The loop that learns",
    "era": "William James and the study of habit",
    "lines": [
      "Habits build the floor",
      "Noticed cues can change the loop",
      "Reward follows form"
    ],
    "body": "Habits build the floor\nNoticed cues can change the loop\nReward follows form",
    "unlockAt": 55,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Principles of Psychology",
    "sourceUrl": "https://www.gutenberg.org/ebooks/57628",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-60-physics",
    "persona": "Orbit Reader",
    "sigil": "軌",
    "category": "advisor-haiku",
    "title": "The law beneath the arc",
    "era": "Motion, light, and scale",
    "lines": [
      "Light bends on the road",
      "Old light arrives from afar",
      "The arc closes home"
    ],
    "body": "Light bends on the road\nOld light arrives from afar\nThe arc closes home",
    "unlockAt": 60,
    "sourceKind": "countku-haiku",
    "sourceLabel": "OpenStax · University Physics",
    "sourceUrl": "https://openstax.org/details/books/university-physics-volume-1",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-65-craft",
    "persona": "Careful Builder",
    "sigil": "作",
    "category": "advisor-haiku",
    "title": "The honest seam",
    "era": "Software craft and deliberate tools",
    "lines": [
      "Good names carry weight",
      "A clear seam keeps change contained",
      "Make each part honest"
    ],
    "body": "Good names carry weight\nA clear seam keeps change contained\nMake each part honest",
    "unlockAt": 65,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Original Countku field notes",
    "sourceUrl": "",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-70-humanism",
    "persona": "Wayside Humanist",
    "sigil": "縁",
    "category": "advisor-haiku",
    "title": "Room at the fire",
    "era": "Montaigne and humane attention",
    "lines": [
      "Questions open doors",
      "Gentle acts outlive the hour",
      "The door opens both"
    ],
    "body": "Questions open doors\nGentle acts outlive the hour\nThe door opens both",
    "unlockAt": 70,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Essays of Montaigne",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3600",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-75-mathematics",
    "persona": "Lantern Geometer",
    "sigil": "∑",
    "category": "advisor-haiku",
    "title": "The patient proof",
    "era": "Euler, number, and proof",
    "lines": [
      "Zero holds its ground",
      "Deep knowledge makes effort small",
      "The pattern breathes on"
    ],
    "body": "Zero holds its ground\nDeep knowledge makes effort small\nThe pattern breathes on",
    "unlockAt": 75,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Euler Archive",
    "sourceUrl": "https://eulerarchive.maa.org/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-80-poetry",
    "persona": "Road Poet",
    "sigil": "句",
    "category": "advisor-haiku",
    "title": "The cut and the echo",
    "era": "Bashō and the short form",
    "lines": [
      "A short line holds worlds",
      "The line ends; the echo stays",
      "Meaning follows breath"
    ],
    "body": "A short line holds worlds\nThe line ends; the echo stays\nMeaning follows breath",
    "unlockAt": 80,
    "sourceKind": "countku-haiku",
    "sourceLabel": "The Narrow Road to the Deep North",
    "sourceUrl": "https://en.wikisource.org/wiki/The_Narrow_Road_to_the_Deep_North",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-85-confucius",
    "persona": "Patient Teacher",
    "sigil": "仁",
    "category": "advisor-haiku",
    "title": "Practice and reflection",
    "era": "The Analects",
    "lines": [
      "Kindness shapes the path",
      "Good conduct begins within",
      "The next step is yours"
    ],
    "body": "Kindness shapes the path\nGood conduct begins within\nThe next step is yours",
    "unlockAt": 85,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Analects",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3330",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-90-strategy",
    "persona": "Quiet Strategist",
    "sigil": "策",
    "category": "advisor-haiku",
    "title": "Before the first move",
    "era": "Sun Tzu and deliberate position",
    "lines": [
      "Shape follows the field",
      "The wise path avoids the wall",
      "Know yourself then cross"
    ],
    "body": "Shape follows the field\nThe wise path avoids the wall\nKnow yourself then cross",
    "unlockAt": 90,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Art of War",
    "sourceUrl": "https://www.gutenberg.org/ebooks/132",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-95-shinto",
    "persona": "Shrine Archivist",
    "sigil": "祓",
    "category": "advisor-haiku",
    "title": "Renewal at the gate",
    "era": "Shinto ritual and renewal",
    "lines": [
      "Old cedar keeps watch",
      "The threshold asks for respect",
      "The old grove stays near"
    ],
    "body": "Old cedar keeps watch\nThe threshold asks for respect\nThe old grove stays near",
    "unlockAt": 95,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Kokugakuin · Encyclopedia of Shinto",
    "sourceUrl": "https://d-museum.kokugakuin.ac.jp/eos/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-100-evolution",
    "persona": "Field Naturalist",
    "sigil": "枝",
    "category": "advisor-haiku",
    "title": "Changes that take root",
    "era": "Darwin and adaptive form",
    "lines": [
      "Old traits find new homes",
      "What thrives depends on the place",
      "Small steps alter worlds"
    ],
    "body": "Old traits find new homes\nWhat thrives depends on the place\nSmall steps alter worlds",
    "unlockAt": 100,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · On the Origin of Species",
    "sourceUrl": "https://www.gutenberg.org/ebooks/1228",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-120-stoicism",
    "persona": "Porch Philosopher",
    "sigil": "選",
    "category": "advisor-haiku",
    "title": "The next right act",
    "era": "Epictetus and Marcus Aurelius",
    "lines": [
      "Guard the inner gate",
      "You choose the meaning you keep",
      "Choose the next right act"
    ],
    "body": "Guard the inner gate\nYou choose the meaning you keep\nChoose the next right act",
    "unlockAt": 120,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Meditations",
    "sourceUrl": "https://www.gutenberg.org/ebooks/2680",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-140-wasan",
    "persona": "Sangaku Keeper",
    "sigil": "算",
    "category": "advisor-haiku",
    "title": "Proof beneath the eaves",
    "era": "Edo-period Japanese mathematics",
    "lines": [
      "Old sums climb the shrine",
      "Each diagram honors craft",
      "The beam holds the proof"
    ],
    "body": "Old sums climb the shrine\nEach diagram honors craft\nThe beam holds the proof",
    "unlockAt": 140,
    "sourceKind": "countku-haiku",
    "sourceLabel": "National Diet Library · Japanese Mathematics",
    "sourceUrl": "https://www.ndl.go.jp/math/e/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-160-tao",
    "persona": "Water Listener",
    "sigil": "道",
    "category": "advisor-haiku",
    "title": "The yielding road",
    "era": "The Tao Te Ching",
    "lines": [
      "The empty cup waits",
      "The yielding path can endure",
      "Less force, farther roads"
    ],
    "body": "The empty cup waits\nThe yielding path can endure\nLess force, farther roads",
    "unlockAt": 160,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Tao Te Ching",
    "sourceUrl": "https://www.gutenberg.org/ebooks/216",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-180-zen",
    "persona": "Bell Keeper",
    "sigil": "無",
    "category": "advisor-haiku",
    "title": "The room already here",
    "era": "Zen practice and direct attention",
    "lines": [
      "No thought needs a crown",
      "No mirror owns what it shows",
      "The bell rings once more"
    ],
    "body": "No thought needs a crown\nNo mirror owns what it shows\nThe bell rings once more",
    "unlockAt": 180,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Sacred Books of the East",
    "sourceUrl": "https://www.sacred-texts.com/bud/zen/index.htm",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-200-psychology",
    "persona": "Habit Cartographer",
    "sigil": "習",
    "category": "advisor-haiku",
    "title": "The loop that learns",
    "era": "William James and the study of habit",
    "lines": [
      "Practice changes sight",
      "The practiced path asks less thought",
      "Practice changes ease"
    ],
    "body": "Practice changes sight\nThe practiced path asks less thought\nPractice changes ease",
    "unlockAt": 200,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Principles of Psychology",
    "sourceUrl": "https://www.gutenberg.org/ebooks/57628",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-220-physics",
    "persona": "Orbit Reader",
    "sigil": "軌",
    "category": "advisor-haiku",
    "title": "The law beneath the arc",
    "era": "Motion, light, and scale",
    "lines": [
      "Stars count without clocks",
      "A curved path still follows rules",
      "The old light finds us"
    ],
    "body": "Stars count without clocks\nA curved path still follows rules\nThe old light finds us",
    "unlockAt": 220,
    "sourceKind": "countku-haiku",
    "sourceLabel": "OpenStax · University Physics",
    "sourceUrl": "https://openstax.org/details/books/university-physics-volume-1",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-240-craft",
    "persona": "Careful Builder",
    "sigil": "作",
    "category": "advisor-haiku",
    "title": "The honest seam",
    "era": "Software craft and deliberate tools",
    "lines": [
      "A clean edge saves time",
      "Good tools vanish into use",
      "Let the code read plain"
    ],
    "body": "A clean edge saves time\nGood tools vanish into use\nLet the code read plain",
    "unlockAt": 240,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Original Countku field notes",
    "sourceUrl": "",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-260-humanism",
    "persona": "Wayside Humanist",
    "sigil": "縁",
    "category": "advisor-haiku",
    "title": "Room at the fire",
    "era": "Montaigne and humane attention",
    "lines": [
      "The stranger bears worlds",
      "Deep listening can change the room",
      "Listen past the words"
    ],
    "body": "The stranger bears worlds\nDeep listening can change the room\nListen past the words",
    "unlockAt": 260,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Essays of Montaigne",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3600",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-280-mathematics",
    "persona": "Lantern Geometer",
    "sigil": "∑",
    "category": "advisor-haiku",
    "title": "The patient proof",
    "era": "Euler, number, and proof",
    "lines": [
      "Proof walks without noise",
      "The arc returns to its start",
      "One sum, many roads"
    ],
    "body": "Proof walks without noise\nThe arc returns to its start\nOne sum, many roads",
    "unlockAt": 280,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Euler Archive",
    "sourceUrl": "https://eulerarchive.maa.org/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-300-poetry",
    "persona": "Road Poet",
    "sigil": "句",
    "category": "advisor-haiku",
    "title": "The cut and the echo",
    "era": "Bashō and the short form",
    "lines": [
      "One image turns thought",
      "Plain words leave the deepest mark",
      "The season stays near"
    ],
    "body": "One image turns thought\nPlain words leave the deepest mark\nThe season stays near",
    "unlockAt": 300,
    "sourceKind": "countku-haiku",
    "sourceLabel": "The Narrow Road to the Deep North",
    "sourceUrl": "https://en.wikisource.org/wiki/The_Narrow_Road_to_the_Deep_North",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-320-confucius",
    "persona": "Patient Teacher",
    "sigil": "仁",
    "category": "advisor-haiku",
    "title": "Practice and reflection",
    "era": "The Analects",
    "lines": [
      "Study then reflect",
      "Thought and study share one lamp",
      "Keep the question warm"
    ],
    "body": "Study then reflect\nThought and study share one lamp\nKeep the question warm",
    "unlockAt": 320,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Analects",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3330",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-340-strategy",
    "persona": "Quiet Strategist",
    "sigil": "策",
    "category": "advisor-haiku",
    "title": "Before the first move",
    "era": "Sun Tzu and deliberate position",
    "lines": [
      "Quiet plans move first",
      "A patient move changes scale",
      "Win before you move"
    ],
    "body": "Quiet plans move first\nA patient move changes scale\nWin before you move",
    "unlockAt": 340,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Art of War",
    "sourceUrl": "https://www.gutenberg.org/ebooks/132",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-360-shinto",
    "persona": "Shrine Archivist",
    "sigil": "祓",
    "category": "advisor-haiku",
    "title": "Renewal at the gate",
    "era": "Shinto ritual and renewal",
    "lines": [
      "Rites can shape the day",
      "A clean path begins in care",
      "The threshold opens"
    ],
    "body": "Rites can shape the day\nA clean path begins in care\nThe threshold opens",
    "unlockAt": 360,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Kokugakuin · Encyclopedia of Shinto",
    "sourceUrl": "https://d-museum.kokugakuin.ac.jp/eos/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-380-evolution",
    "persona": "Field Naturalist",
    "sigil": "枝",
    "category": "advisor-haiku",
    "title": "Changes that take root",
    "era": "Darwin and adaptive form",
    "lines": [
      "Chance walks beside need",
      "A slight edge can alter paths",
      "The branch tells the tale"
    ],
    "body": "Chance walks beside need\nA slight edge can alter paths\nThe branch tells the tale",
    "unlockAt": 380,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · On the Origin of Species",
    "sourceUrl": "https://www.gutenberg.org/ebooks/1228",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-400-stoicism",
    "persona": "Porch Philosopher",
    "sigil": "選",
    "category": "advisor-haiku",
    "title": "The next right act",
    "era": "Epictetus and Marcus Aurelius",
    "lines": [
      "The mind meets the storm",
      "Meet what arrives without masks",
      "The storm passes through"
    ],
    "body": "The mind meets the storm\nMeet what arrives without masks\nThe storm passes through",
    "unlockAt": 400,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Meditations",
    "sourceUrl": "https://www.gutenberg.org/ebooks/2680",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-420-wasan",
    "persona": "Sangaku Keeper",
    "sigil": "算",
    "category": "advisor-haiku",
    "title": "Proof beneath the eaves",
    "era": "Edo-period Japanese mathematics",
    "lines": [
      "Wooden tablets speak",
      "A bright theorem greets the dawn",
      "The shape bows to thought"
    ],
    "body": "Wooden tablets speak\nA bright theorem greets the dawn\nThe shape bows to thought",
    "unlockAt": 420,
    "sourceKind": "countku-haiku",
    "sourceLabel": "National Diet Library · Japanese Mathematics",
    "sourceUrl": "https://www.ndl.go.jp/math/e/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-440-tao",
    "persona": "Water Listener",
    "sigil": "道",
    "category": "advisor-haiku",
    "title": "The yielding road",
    "era": "The Tao Te Ching",
    "lines": [
      "Soft paths wear down stone",
      "No fixed shape survives each stream",
      "Bend and still remain"
    ],
    "body": "Soft paths wear down stone\nNo fixed shape survives each stream\nBend and still remain",
    "unlockAt": 440,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Tao Te Ching",
    "sourceUrl": "https://www.gutenberg.org/ebooks/216",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-460-zen",
    "persona": "Bell Keeper",
    "sigil": "無",
    "category": "advisor-haiku",
    "title": "The room already here",
    "era": "Zen practice and direct attention",
    "lines": [
      "Breath returns the room",
      "A question dissolves in breath",
      "The room was right here"
    ],
    "body": "Breath returns the room\nA question dissolves in breath\nThe room was right here",
    "unlockAt": 460,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Sacred Books of the East",
    "sourceUrl": "https://www.sacred-texts.com/bud/zen/index.htm",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-480-psychology",
    "persona": "Habit Cartographer",
    "sigil": "習",
    "category": "advisor-haiku",
    "title": "The loop that learns",
    "era": "William James and the study of habit",
    "lines": [
      "The story shapes choice",
      "Attention makes signals loud",
      "Notice, pause, then choose"
    ],
    "body": "The story shapes choice\nAttention makes signals loud\nNotice, pause, then choose",
    "unlockAt": 480,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Principles of Psychology",
    "sourceUrl": "https://www.gutenberg.org/ebooks/57628",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-500-physics",
    "persona": "Orbit Reader",
    "sigil": "軌",
    "category": "advisor-haiku",
    "title": "The law beneath the arc",
    "era": "Motion, light, and scale",
    "lines": [
      "Gravity writes arcs",
      "Orbits remember each pull",
      "The orbit comes round"
    ],
    "body": "Gravity writes arcs\nOrbits remember each pull\nThe orbit comes round",
    "unlockAt": 500,
    "sourceKind": "countku-haiku",
    "sourceLabel": "OpenStax · University Physics",
    "sourceUrl": "https://openstax.org/details/books/university-physics-volume-1",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-520-craft",
    "persona": "Careful Builder",
    "sigil": "作",
    "category": "advisor-haiku",
    "title": "The honest seam",
    "era": "Software craft and deliberate tools",
    "lines": [
      "Tools shape willing hands",
      "A short path can still explain",
      "Names become small maps"
    ],
    "body": "Tools shape willing hands\nA short path can still explain\nNames become small maps",
    "unlockAt": 520,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Original Countku field notes",
    "sourceUrl": "",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-540-humanism",
    "persona": "Wayside Humanist",
    "sigil": "縁",
    "category": "advisor-haiku",
    "title": "Room at the fire",
    "era": "Montaigne and humane attention",
    "lines": [
      "One voice steadies two",
      "Honest words make room for two",
      "Leave room at the fire"
    ],
    "body": "One voice steadies two\nHonest words make room for two\nLeave room at the fire",
    "unlockAt": 540,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Essays of Montaigne",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3600",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-560-mathematics",
    "persona": "Lantern Geometer",
    "sigil": "∑",
    "category": "advisor-haiku",
    "title": "The patient proof",
    "era": "Euler, number, and proof",
    "lines": [
      "Curves remember light",
      "Patient symbols shape the road",
      "Exactness can sing"
    ],
    "body": "Curves remember light\nPatient symbols shape the road\nExactness can sing",
    "unlockAt": 560,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Euler Archive",
    "sourceUrl": "https://eulerarchive.maa.org/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-580-poetry",
    "persona": "Road Poet",
    "sigil": "句",
    "category": "advisor-haiku",
    "title": "The cut and the echo",
    "era": "Bashō and the short form",
    "lines": [
      "Petals mark the pause",
      "Small forms can hold a wide sky",
      "The image walks home"
    ],
    "body": "Petals mark the pause\nSmall forms can hold a wide sky\nThe image walks home",
    "unlockAt": 580,
    "sourceKind": "countku-haiku",
    "sourceLabel": "The Narrow Road to the Deep North",
    "sourceUrl": "https://en.wikisource.org/wiki/The_Narrow_Road_to_the_Deep_North",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-600-confucius",
    "persona": "Patient Teacher",
    "sigil": "仁",
    "category": "advisor-haiku",
    "title": "Practice and reflection",
    "era": "The Analects",
    "lines": [
      "Honor roots the self",
      "The honest path needs no mask",
      "Let practice take root"
    ],
    "body": "Honor roots the self\nThe honest path needs no mask\nLet practice take root",
    "unlockAt": 600,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Analects",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3330",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-620-strategy",
    "persona": "Quiet Strategist",
    "sigil": "策",
    "category": "advisor-haiku",
    "title": "Before the first move",
    "era": "Sun Tzu and deliberate position",
    "lines": [
      "Know the ground you cross",
      "Deep knowledge makes effort small",
      "The quiet line holds"
    ],
    "body": "Know the ground you cross\nDeep knowledge makes effort small\nThe quiet line holds",
    "unlockAt": 620,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Art of War",
    "sourceUrl": "https://www.gutenberg.org/ebooks/132",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-640-shinto",
    "persona": "Shrine Archivist",
    "sigil": "祓",
    "category": "advisor-haiku",
    "title": "Renewal at the gate",
    "era": "Shinto ritual and renewal",
    "lines": [
      "The gate marks a change",
      "Names carry the weight we give",
      "Step lightly, then bow"
    ],
    "body": "The gate marks a change\nNames carry the weight we give\nStep lightly, then bow",
    "unlockAt": 640,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Kokugakuin · Encyclopedia of Shinto",
    "sourceUrl": "https://d-museum.kokugakuin.ac.jp/eos/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-660-evolution",
    "persona": "Field Naturalist",
    "sigil": "枝",
    "category": "advisor-haiku",
    "title": "Changes that take root",
    "era": "Darwin and adaptive form",
    "lines": [
      "Forms answer the world",
      "Each answer bears its own cost",
      "The field writes the shape"
    ],
    "body": "Forms answer the world\nEach answer bears its own cost\nThe field writes the shape",
    "unlockAt": 660,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · On the Origin of Species",
    "sourceUrl": "https://www.gutenberg.org/ebooks/1228",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-680-stoicism",
    "persona": "Porch Philosopher",
    "sigil": "選",
    "category": "advisor-haiku",
    "title": "The next right act",
    "era": "Epictetus and Marcus Aurelius",
    "lines": [
      "Judgment colors pain",
      "A clear act answers the day",
      "Hold the center still"
    ],
    "body": "Judgment colors pain\nA clear act answers the day\nHold the center still",
    "unlockAt": 680,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Meditations",
    "sourceUrl": "https://www.gutenberg.org/ebooks/2680",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-700-wasan",
    "persona": "Sangaku Keeper",
    "sigil": "算",
    "category": "advisor-haiku",
    "title": "Proof beneath the eaves",
    "era": "Edo-period Japanese mathematics",
    "lines": [
      "Proof hangs under eaves",
      "A circle answers a square",
      "The answer hangs near"
    ],
    "body": "Proof hangs under eaves\nA circle answers a square\nThe answer hangs near",
    "unlockAt": 700,
    "sourceKind": "countku-haiku",
    "sourceLabel": "National Diet Library · Japanese Mathematics",
    "sourceUrl": "https://www.ndl.go.jp/math/e/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-720-tao",
    "persona": "Water Listener",
    "sigil": "道",
    "category": "advisor-haiku",
    "title": "The yielding road",
    "era": "The Tao Te Ching",
    "lines": [
      "Water finds the low",
      "Usefulness grows from empty",
      "Let the current teach"
    ],
    "body": "Water finds the low\nUsefulness grows from empty\nLet the current teach",
    "unlockAt": 720,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Tao Te Ching",
    "sourceUrl": "https://www.gutenberg.org/ebooks/216",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-740-zen",
    "persona": "Bell Keeper",
    "sigil": "無",
    "category": "advisor-haiku",
    "title": "The room already here",
    "era": "Zen practice and direct attention",
    "lines": [
      "Sit before the fact",
      "The still seat crosses great miles",
      "Leave the door unbarred"
    ],
    "body": "Sit before the fact\nThe still seat crosses great miles\nLeave the door unbarred",
    "unlockAt": 740,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Sacred Books of the East",
    "sourceUrl": "https://www.sacred-texts.com/bud/zen/index.htm",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-760-psychology",
    "persona": "Habit Cartographer",
    "sigil": "習",
    "category": "advisor-haiku",
    "title": "The loop that learns",
    "era": "William James and the study of habit",
    "lines": [
      "Small rewards steer feet",
      "A habit becomes a road",
      "The loop learns from you"
    ],
    "body": "Small rewards steer feet\nA habit becomes a road\nThe loop learns from you",
    "unlockAt": 760,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Principles of Psychology",
    "sourceUrl": "https://www.gutenberg.org/ebooks/57628",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-780-physics",
    "persona": "Orbit Reader",
    "sigil": "軌",
    "category": "advisor-haiku",
    "title": "The law beneath the arc",
    "era": "Motion, light, and scale",
    "lines": [
      "Atoms trade their songs",
      "The void hums beneath each form",
      "Each law leaves a trace"
    ],
    "body": "Atoms trade their songs\nThe void hums beneath each form\nEach law leaves a trace",
    "unlockAt": 780,
    "sourceKind": "countku-haiku",
    "sourceLabel": "OpenStax · University Physics",
    "sourceUrl": "https://openstax.org/details/books/university-physics-volume-1",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-800-craft",
    "persona": "Careful Builder",
    "sigil": "作",
    "category": "advisor-haiku",
    "title": "The honest seam",
    "era": "Software craft and deliberate tools",
    "lines": [
      "Plain code leaves a trail",
      "The craft lives in careful cuts",
      "The tool leaves no scar"
    ],
    "body": "Plain code leaves a trail\nThe craft lives in careful cuts\nThe tool leaves no scar",
    "unlockAt": 800,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Original Countku field notes",
    "sourceUrl": "",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-820-humanism",
    "persona": "Wayside Humanist",
    "sigil": "縁",
    "category": "advisor-haiku",
    "title": "Room at the fire",
    "era": "Montaigne and humane attention",
    "lines": [
      "Kindness crosses time",
      "Strangers can carry your key",
      "Kindness keeps its reach"
    ],
    "body": "Kindness crosses time\nStrangers can carry your key\nKindness keeps its reach",
    "unlockAt": 820,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Essays of Montaigne",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3600",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-840-mathematics",
    "persona": "Lantern Geometer",
    "sigil": "∑",
    "category": "advisor-haiku",
    "title": "The patient proof",
    "era": "Euler, number, and proof",
    "lines": [
      "Patterns turn the key",
      "Old questions open new doors",
      "The whole path grows clear"
    ],
    "body": "Patterns turn the key\nOld questions open new doors\nThe whole path grows clear",
    "unlockAt": 840,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Euler Archive",
    "sourceUrl": "https://eulerarchive.maa.org/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-860-poetry",
    "persona": "Road Poet",
    "sigil": "句",
    "category": "advisor-haiku",
    "title": "The cut and the echo",
    "era": "Bashō and the short form",
    "lines": [
      "The old pond keeps time",
      "A season enters one word",
      "One line opens twice"
    ],
    "body": "The old pond keeps time\nA season enters one word\nOne line opens twice",
    "unlockAt": 860,
    "sourceKind": "countku-haiku",
    "sourceLabel": "The Narrow Road to the Deep North",
    "sourceUrl": "https://en.wikisource.org/wiki/The_Narrow_Road_to_the_Deep_North",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-880-confucius",
    "persona": "Patient Teacher",
    "sigil": "仁",
    "category": "advisor-haiku",
    "title": "Practice and reflection",
    "era": "The Analects",
    "lines": [
      "Practice steadies thought",
      "The careful learner looks back",
      "Begin with the self"
    ],
    "body": "Practice steadies thought\nThe careful learner looks back\nBegin with the self",
    "unlockAt": 880,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Analects",
    "sourceUrl": "https://www.gutenberg.org/ebooks/3330",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-900-strategy",
    "persona": "Quiet Strategist",
    "sigil": "策",
    "category": "advisor-haiku",
    "title": "Before the first move",
    "era": "Sun Tzu and deliberate position",
    "lines": [
      "The right place bends fate",
      "Clear eyes prepare before steps",
      "Leave no wasted step"
    ],
    "body": "The right place bends fate\nClear eyes prepare before steps\nLeave no wasted step",
    "unlockAt": 900,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · The Art of War",
    "sourceUrl": "https://www.gutenberg.org/ebooks/132",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-920-shinto",
    "persona": "Shrine Archivist",
    "sigil": "祓",
    "category": "advisor-haiku",
    "title": "Renewal at the gate",
    "era": "Shinto ritual and renewal",
    "lines": [
      "Clear water, clear mind",
      "Each season teaches return",
      "Begin clean again"
    ],
    "body": "Clear water, clear mind\nEach season teaches return\nBegin clean again",
    "unlockAt": 920,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Kokugakuin · Encyclopedia of Shinto",
    "sourceUrl": "https://d-museum.kokugakuin.ac.jp/eos/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-940-evolution",
    "persona": "Field Naturalist",
    "sigil": "枝",
    "category": "advisor-haiku",
    "title": "Changes that take root",
    "era": "Darwin and adaptive form",
    "lines": [
      "Life branches through time",
      "The fit changes with the field",
      "Time keeps every mark"
    ],
    "body": "Life branches through time\nThe fit changes with the field\nTime keeps every mark",
    "unlockAt": 940,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · On the Origin of Species",
    "sourceUrl": "https://www.gutenberg.org/ebooks/1228",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-960-stoicism",
    "persona": "Porch Philosopher",
    "sigil": "選",
    "category": "advisor-haiku",
    "title": "The next right act",
    "era": "Epictetus and Marcus Aurelius",
    "lines": [
      "Events pass through us",
      "The next choice belongs to you",
      "Let judgment rest now"
    ],
    "body": "Events pass through us\nThe next choice belongs to you\nLet judgment rest now",
    "unlockAt": 960,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Meditations",
    "sourceUrl": "https://www.gutenberg.org/ebooks/2680",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-980-wasan",
    "persona": "Sangaku Keeper",
    "sigil": "算",
    "category": "advisor-haiku",
    "title": "Proof beneath the eaves",
    "era": "Edo-period Japanese mathematics",
    "lines": [
      "Circles meet the beam",
      "Old shrines keep questions alive",
      "Old craft becomes new"
    ],
    "body": "Circles meet the beam\nOld shrines keep questions alive\nOld craft becomes new",
    "unlockAt": 980,
    "sourceKind": "countku-haiku",
    "sourceLabel": "National Diet Library · Japanese Mathematics",
    "sourceUrl": "https://www.ndl.go.jp/math/e/",
    "sourceAccessed": "2026-07-28"
  },
  {
    "id": "advisor-1000-tao",
    "persona": "Water Listener",
    "sigil": "道",
    "category": "advisor-haiku",
    "title": "The yielding road",
    "era": "The Tao Te Ching",
    "lines": [
      "Valleys remain wide",
      "The way appears as we walk",
      "Return without fear"
    ],
    "body": "Valleys remain wide\nThe way appears as we walk\nReturn without fear",
    "unlockAt": 1000,
    "sourceKind": "countku-haiku",
    "sourceLabel": "Project Gutenberg · Tao Te Ching",
    "sourceUrl": "https://www.gutenberg.org/ebooks/216",
    "sourceAccessed": "2026-07-28"
  }
];
const fields = [
  {
    "id": "avatar-pride-source",
    "persona": "Iroh",
    "title": "The source of shame",
    "era": "Avatar · Bitter Work",
    "body": "Pride is not the opposite of shame, but its source.",
    "sourceKind": "scene",
    "sourceLabel": "Bitter Work transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ABitter_Work"
  },
  {
    "id": "avatar-many-places",
    "persona": "Iroh",
    "title": "Many places",
    "era": "Avatar · Bitter Work",
    "body": "It is important to draw wisdom from many different places.",
    "sourceKind": "scene",
    "sourceLabel": "Bitter Work transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ABitter_Work"
  },
  {
    "id": "avatar-life-happens",
    "persona": "Iroh",
    "title": "Wherever you are",
    "era": "Avatar · City of Walls and Secrets",
    "body": "Life happens wherever you are, whether you make it or not.",
    "sourceKind": "scene",
    "sourceLabel": "City of Walls and Secrets transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ACity_of_Walls_and_Secrets"
  },
  {
    "id": "avatar-power-overrated",
    "persona": "Iroh",
    "title": "Power, reconsidered",
    "era": "Avatar · The Crossroads of Destiny",
    "body": "Perfection and power are overrated.",
    "sourceKind": "scene",
    "sourceLabel": "The Crossroads of Destiny transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Crossroads_of_Destiny"
  },
  {
    "id": "avatar-dark-tunnel",
    "persona": "Iroh",
    "title": "The dark tunnel",
    "era": "Avatar · The Crossroads of Destiny",
    "body": "Sometimes, life is like this dark tunnel.",
    "sourceKind": "scene",
    "sourceLabel": "The Crossroads of Destiny transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Crossroads_of_Destiny"
  },
  {
    "id": "avatar-five-seven-five",
    "persona": "Macmu-Ling",
    "title": "Remarkable oaf",
    "era": "Avatar · The Tales of Ba Sing Se",
    "body": "Five, seven, then five, syllables mark a haiku. Remarkable oaf.",
    "sourceKind": "scene",
    "sourceLabel": "The Tales of Ba Sing Se transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Tales_of_Ba_Sing_Se"
  },
  {
    "id": "avatar-help-another",
    "persona": "Iroh",
    "title": "Help someone else",
    "era": "Korra · A New Spiritual Age",
    "body": "Sometimes the best way to solve your own problems is to help someone else.",
    "sourceKind": "scene",
    "sourceLabel": "A New Spiritual Age transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AA_New_Spiritual_Age"
  },
  {
    "id": "avatar-light-inside",
    "persona": "Iroh",
    "title": "Light inside",
    "era": "Korra · A New Spiritual Age",
    "body": "But you have light and peace inside of you.",
    "sourceKind": "scene",
    "sourceLabel": "A New Spiritual Age transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AA_New_Spiritual_Age"
  },
  {
    "id": "avatar-hard-forgive",
    "persona": "Aang",
    "title": "The harder act",
    "era": "Avatar · The Southern Raiders",
    "body": "It's easy to do nothing, but it's hard to forgive.",
    "sourceKind": "scene",
    "sourceLabel": "The Southern Raiders transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Southern_Raiders"
  },
  {
    "id": "avatar-first-healing",
    "persona": "Aang",
    "title": "The first step",
    "era": "Avatar · The Southern Raiders",
    "body": "Forgiveness is the first step you have to take to begin healing.",
    "sourceKind": "scene",
    "sourceLabel": "The Southern Raiders transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Southern_Raiders"
  },
  {
    "id": "avatar-separation",
    "persona": "Guru Pathik",
    "title": "The great illusion",
    "era": "Avatar · The Guru",
    "body": "The greatest illusion of this world is the illusion of separation.",
    "sourceKind": "scene",
    "sourceLabel": "The Guru transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Guru"
  },
  {
    "id": "avatar-no-despair",
    "persona": "Iroh",
    "title": "Do not surrender",
    "era": "Avatar · Avatar Day",
    "body": "You must never give in to despair.",
    "sourceKind": "scene",
    "sourceLabel": "Avatar Day transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AAvatar_Day"
  },
  {
    "id": "avatar-give-hope",
    "persona": "Iroh",
    "title": "Hope is given",
    "era": "Avatar · Avatar Day",
    "body": "In the darkest times, hope is something you give yourself.",
    "sourceKind": "scene",
    "sourceLabel": "Avatar Day transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AAvatar_Day"
  },
  {
    "id": "avatar-tea-stranger",
    "persona": "Iroh",
    "title": "A true delight",
    "era": "Avatar · The Chase",
    "body": "Sharing tea with a fascinating stranger is one of life's true delights.",
    "sourceKind": "scene",
    "sourceLabel": "The Chase transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Chase"
  },
  {
    "id": "avatar-let-love-help",
    "persona": "Iroh",
    "title": "Let love help",
    "era": "Avatar · The Chase",
    "body": "There is nothing wrong with letting the people who love you help you.",
    "sourceKind": "scene",
    "sourceLabel": "The Chase transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Chase"
  },
  {
    "id": "avatar-destiny-funny",
    "persona": "Iroh",
    "title": "A funny thing",
    "era": "Avatar · The Western Air Temple",
    "body": "Destiny is a funny thing.",
    "sourceKind": "scene",
    "sourceLabel": "The Western Air Temple transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Western_Air_Temple"
  },
  {
    "id": "avatar-open-future",
    "persona": "Iroh",
    "title": "An open future",
    "era": "Avatar · The Western Air Temple",
    "body": "You never know how things are going to work out.",
    "sourceKind": "scene",
    "sourceLabel": "The Western Air Temple transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Western_Air_Temple"
  },
  {
    "id": "avatar-true-mind",
    "persona": "Avatar Aang",
    "title": "The true mind",
    "era": "Korra · Turf Wars, Part Three",
    "body": "The true mind can weather all the lies and illusions without being lost.",
    "sourceKind": "scene",
    "sourceLabel": "Turf Wars Part Three transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ATurf_Wars_Part_Three"
  },
  {
    "id": "avatar-earthly-tether",
    "persona": "Guru Laghima",
    "title": "Become wind",
    "era": "Korra · Enter the Void",
    "body": "Let go your earthly tether. Enter the void. Empty and become wind.",
    "sourceKind": "scene",
    "sourceLabel": "Enter the Void transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AEnter_the_Void"
  },
  {
    "id": "avatar-never-angry",
    "persona": "Iroh",
    "title": "The way home",
    "era": "Avatar · Sozin's Comet",
    "body": "I was never angry with you.",
    "sourceKind": "scene",
    "sourceLabel": "The Old Masters transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ASozin%27s_Comet%2C_Part_2%3A_The_Old_Masters"
  },
  {
    "id": "field-oak-count-now",
    "persona": "Professor Oak's echo",
    "title": "A time and place",
    "era": "Countku field note",
    "body": "Professor Oak's words echoed: “There's a time and place for everything. We count now.”",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-breath-before-proof",
    "persona": "The road",
    "title": "Before the proof",
    "era": "Countku field note",
    "body": "Breathe once. The answer is not improved by arriving tense.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-cube-eight",
    "persona": "The road",
    "title": "Under the influence",
    "era": "Countku field note",
    "body": "The cube root of eight under the influence of the power of eight, type shit.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-small-form",
    "persona": "The road",
    "title": "Seventeen",
    "era": "Countku field note",
    "body": "A tiny form can still carry an unnecessarily large idea.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-moon-math",
    "persona": "The road",
    "title": "Moon arithmetic",
    "era": "Countku field note",
    "body": "The moon has declined to show its work. Countku has filed an appeal.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-patient-root",
    "persona": "The road",
    "title": "Root patience",
    "era": "Countku field note",
    "body": "A root does not hurry. It simply keeps being correct underground.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-no-padding",
    "persona": "The road",
    "title": "No padding",
    "era": "Countku field note",
    "body": "The cleanest landing is the one that did not need extra furniture.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-ordinal-museum",
    "persona": "The road",
    "title": "Old names",
    "era": "Countku field note",
    "body": "Quartic, tessaric, tetradic: the museum gift shop remains open.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-silver-sandwich",
    "persona": "The road",
    "title": "A silver sandwich",
    "era": "Countku field note",
    "body": "Clouds have two sides. The snack situation remains mathematically unresolved.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-threshold",
    "persona": "The road",
    "title": "Five more",
    "era": "Countku field note",
    "body": "The next forest is five exact landings away. It is already choosing a color.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-sokka-six",
    "persona": "The road",
    "title": "One too many",
    "era": "Countku field note",
    "body": "A sixth syllable approaches. The bouncer has noticed.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  },
  {
    "id": "field-equation-listens",
    "persona": "The road",
    "title": "Listening",
    "era": "Countku field note",
    "body": "Say the equation plainly enough and even the forest starts counting.",
    "sourceKind": "original",
    "sourceLabel": "Original Countku dialogue",
    "sourceUrl": ""
  }
];
const scenes = [
  {
    "id": "avatar-pride-source",
    "persona": "Iroh",
    "title": "The source of shame",
    "era": "Avatar · Bitter Work",
    "body": "Pride is not the opposite of shame, but its source.",
    "sourceKind": "scene",
    "sourceLabel": "Bitter Work transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ABitter_Work"
  },
  {
    "id": "avatar-many-places",
    "persona": "Iroh",
    "title": "Many places",
    "era": "Avatar · Bitter Work",
    "body": "It is important to draw wisdom from many different places.",
    "sourceKind": "scene",
    "sourceLabel": "Bitter Work transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ABitter_Work"
  },
  {
    "id": "avatar-life-happens",
    "persona": "Iroh",
    "title": "Wherever you are",
    "era": "Avatar · City of Walls and Secrets",
    "body": "Life happens wherever you are, whether you make it or not.",
    "sourceKind": "scene",
    "sourceLabel": "City of Walls and Secrets transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ACity_of_Walls_and_Secrets"
  },
  {
    "id": "avatar-power-overrated",
    "persona": "Iroh",
    "title": "Power, reconsidered",
    "era": "Avatar · The Crossroads of Destiny",
    "body": "Perfection and power are overrated.",
    "sourceKind": "scene",
    "sourceLabel": "The Crossroads of Destiny transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Crossroads_of_Destiny"
  },
  {
    "id": "avatar-dark-tunnel",
    "persona": "Iroh",
    "title": "The dark tunnel",
    "era": "Avatar · The Crossroads of Destiny",
    "body": "Sometimes, life is like this dark tunnel.",
    "sourceKind": "scene",
    "sourceLabel": "The Crossroads of Destiny transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Crossroads_of_Destiny"
  },
  {
    "id": "avatar-five-seven-five",
    "persona": "Macmu-Ling",
    "title": "Remarkable oaf",
    "era": "Avatar · The Tales of Ba Sing Se",
    "body": "Five, seven, then five, syllables mark a haiku. Remarkable oaf.",
    "sourceKind": "scene",
    "sourceLabel": "The Tales of Ba Sing Se transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Tales_of_Ba_Sing_Se"
  },
  {
    "id": "avatar-help-another",
    "persona": "Iroh",
    "title": "Help someone else",
    "era": "Korra · A New Spiritual Age",
    "body": "Sometimes the best way to solve your own problems is to help someone else.",
    "sourceKind": "scene",
    "sourceLabel": "A New Spiritual Age transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AA_New_Spiritual_Age"
  },
  {
    "id": "avatar-light-inside",
    "persona": "Iroh",
    "title": "Light inside",
    "era": "Korra · A New Spiritual Age",
    "body": "But you have light and peace inside of you.",
    "sourceKind": "scene",
    "sourceLabel": "A New Spiritual Age transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AA_New_Spiritual_Age"
  },
  {
    "id": "avatar-hard-forgive",
    "persona": "Aang",
    "title": "The harder act",
    "era": "Avatar · The Southern Raiders",
    "body": "It's easy to do nothing, but it's hard to forgive.",
    "sourceKind": "scene",
    "sourceLabel": "The Southern Raiders transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Southern_Raiders"
  },
  {
    "id": "avatar-first-healing",
    "persona": "Aang",
    "title": "The first step",
    "era": "Avatar · The Southern Raiders",
    "body": "Forgiveness is the first step you have to take to begin healing.",
    "sourceKind": "scene",
    "sourceLabel": "The Southern Raiders transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Southern_Raiders"
  },
  {
    "id": "avatar-separation",
    "persona": "Guru Pathik",
    "title": "The great illusion",
    "era": "Avatar · The Guru",
    "body": "The greatest illusion of this world is the illusion of separation.",
    "sourceKind": "scene",
    "sourceLabel": "The Guru transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Guru"
  },
  {
    "id": "avatar-no-despair",
    "persona": "Iroh",
    "title": "Do not surrender",
    "era": "Avatar · Avatar Day",
    "body": "You must never give in to despair.",
    "sourceKind": "scene",
    "sourceLabel": "Avatar Day transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AAvatar_Day"
  },
  {
    "id": "avatar-give-hope",
    "persona": "Iroh",
    "title": "Hope is given",
    "era": "Avatar · Avatar Day",
    "body": "In the darkest times, hope is something you give yourself.",
    "sourceKind": "scene",
    "sourceLabel": "Avatar Day transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AAvatar_Day"
  },
  {
    "id": "avatar-tea-stranger",
    "persona": "Iroh",
    "title": "A true delight",
    "era": "Avatar · The Chase",
    "body": "Sharing tea with a fascinating stranger is one of life's true delights.",
    "sourceKind": "scene",
    "sourceLabel": "The Chase transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Chase"
  },
  {
    "id": "avatar-let-love-help",
    "persona": "Iroh",
    "title": "Let love help",
    "era": "Avatar · The Chase",
    "body": "There is nothing wrong with letting the people who love you help you.",
    "sourceKind": "scene",
    "sourceLabel": "The Chase transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Chase"
  },
  {
    "id": "avatar-destiny-funny",
    "persona": "Iroh",
    "title": "A funny thing",
    "era": "Avatar · The Western Air Temple",
    "body": "Destiny is a funny thing.",
    "sourceKind": "scene",
    "sourceLabel": "The Western Air Temple transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Western_Air_Temple"
  },
  {
    "id": "avatar-open-future",
    "persona": "Iroh",
    "title": "An open future",
    "era": "Avatar · The Western Air Temple",
    "body": "You never know how things are going to work out.",
    "sourceKind": "scene",
    "sourceLabel": "The Western Air Temple transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AThe_Western_Air_Temple"
  },
  {
    "id": "avatar-true-mind",
    "persona": "Avatar Aang",
    "title": "The true mind",
    "era": "Korra · Turf Wars, Part Three",
    "body": "The true mind can weather all the lies and illusions without being lost.",
    "sourceKind": "scene",
    "sourceLabel": "Turf Wars Part Three transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ATurf_Wars_Part_Three"
  },
  {
    "id": "avatar-earthly-tether",
    "persona": "Guru Laghima",
    "title": "Become wind",
    "era": "Korra · Enter the Void",
    "body": "Let go your earthly tether. Enter the void. Empty and become wind.",
    "sourceKind": "scene",
    "sourceLabel": "Enter the Void transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3AEnter_the_Void"
  },
  {
    "id": "avatar-never-angry",
    "persona": "Iroh",
    "title": "The way home",
    "era": "Avatar · Sozin's Comet",
    "body": "I was never angry with you.",
    "sourceKind": "scene",
    "sourceLabel": "The Old Masters transcript",
    "sourceUrl": "https://avatar.fandom.com/wiki/Transcript%3ASozin%27s_Comet%2C_Part_2%3A_The_Old_Masters"
  }
];

export const ADVISOR_BANK = Object.freeze(
  advisors.map((entry) => Object.freeze({
    ...entry,
    lines: Object.freeze([...entry.lines])
  }))
);

export const FIELD_MESSAGES = Object.freeze(
  fields.map((entry) => Object.freeze(entry))
);

export const AVATAR_SCENE_LINES = Object.freeze(
  scenes.map((entry) => Object.freeze(entry))
);

const normalizeLevel = (value) =>
  Math.max(0, Math.floor(Number(value) || 0));

export function advisorAtLevel(level) {
  const exact = normalizeLevel(level);
  return ADVISOR_BANK.find((entry) => entry.unlockAt === exact) ?? null;
}

export function fieldMessageAtLevel(level) {
  const exact = normalizeLevel(level);
  if (exact === 2) {
    return FIELD_MESSAGES.find(
      (entry) => entry.id === "field-oak-count-now"
    ) ?? null;
  }
  if (exact < 2 || exact % 3 !== 2 || exact % 5 === 0) return null;
  const pool = FIELD_MESSAGES.filter(
    (entry) => entry.id !== "field-oak-count-now"
  );
  const index = Math.floor(exact / 3) % pool.length;
  return pool[index];
}
