// Generated by Orc from sharpjs-countku-worlds.fs.
// Edit the F# source; do not hand-edit this rendered module.
const authored = [
  {
    "id": "sakura-trail",
    "minimum": 0,
    "label": "Sakura Trail",
    "sigil": "桜",
    "description": "The native pink trail: quiet petals, first landings, and an open road.",
    "palette": {
      "accent": "#ff83b8",
      "accentSoft": "#ffd0e3",
      "gold": "#ffd57a",
      "mint": "#8ff0cd",
      "moon": "#d9e3ff",
      "panel": "rgba(17, 17, 41, 0.94)",
      "line": "rgba(211, 220, 255, 0.17)",
      "glowA": "rgba(113, 127, 230, 0.18)",
      "glowB": "rgba(255, 107, 161, 0.15)",
      "top": "#0b0b1c",
      "middle": "#171830",
      "bottom": "#29182f",
      "treeFilter": "saturate(0.82) hue-rotate(12deg) contrast(1.12)"
    }
  },
  {
    "id": "white-forest",
    "minimum": 5,
    "label": "White Forest",
    "sigil": "白",
    "description": "Pale leaves and young green light make the first change unmistakable.",
    "palette": {
      "accent": "#ecfff7",
      "accentSoft": "#ffffff",
      "gold": "#f3e7a4",
      "mint": "#9ee8c7",
      "moon": "#eaf4ff",
      "panel": "rgba(9, 25, 24, 0.95)",
      "line": "rgba(227, 255, 246, 0.2)",
      "glowA": "rgba(213, 255, 240, 0.18)",
      "glowB": "rgba(152, 226, 190, 0.15)",
      "top": "#071513",
      "middle": "#102723",
      "bottom": "#1a332c",
      "treeFilter": "grayscale(0.5) sepia(0.18) hue-rotate(72deg) brightness(1.22)"
    }
  },
  {
    "id": "lantern-vale",
    "minimum": 10,
    "label": "Lantern Vale",
    "sigil": "灯",
    "description": "A warm path begins answering the player with its own light.",
    "palette": {
      "accent": "#ffbc76",
      "accentSoft": "#ffe7bd",
      "gold": "#ffd16c",
      "mint": "#9ce7cc",
      "moon": "#e8efff",
      "panel": "rgba(31, 19, 20, 0.95)",
      "line": "rgba(255, 222, 184, 0.18)",
      "glowA": "rgba(255, 169, 87, 0.21)",
      "glowB": "rgba(142, 220, 195, 0.11)",
      "top": "#170b11",
      "middle": "#2c181a",
      "bottom": "#3a2520",
      "treeFilter": "sepia(0.46) hue-rotate(326deg) saturate(1.18)"
    }
  },
  {
    "id": "cedar-echo",
    "minimum": 15,
    "label": "Cedar Echo",
    "sigil": "杉",
    "description": "Deep wood, restrained gold, and a score that leaves room for breath.",
    "palette": {
      "accent": "#9dd6ad",
      "accentSoft": "#e1f4dc",
      "gold": "#e8c978",
      "mint": "#8ed9c7",
      "moon": "#d6e6f2",
      "panel": "rgba(10, 24, 21, 0.95)",
      "line": "rgba(205, 240, 219, 0.17)",
      "glowA": "rgba(87, 164, 120, 0.2)",
      "glowB": "rgba(214, 177, 91, 0.1)",
      "top": "#07120e",
      "middle": "#13241b",
      "bottom": "#243126",
      "treeFilter": "sepia(0.26) hue-rotate(82deg) saturate(0.86)"
    }
  },
  {
    "id": "amber-steppe",
    "minimum": 20,
    "label": "Amber Steppe",
    "sigil": "琥",
    "description": "The first full score movement opens beneath a long amber horizon.",
    "palette": {
      "accent": "#eeb66b",
      "accentSoft": "#ffe6b5",
      "gold": "#ffd487",
      "mint": "#a6e0c4",
      "moon": "#e7e7dd",
      "panel": "rgba(29, 20, 12, 0.95)",
      "line": "rgba(255, 222, 170, 0.18)",
      "glowA": "rgba(242, 169, 73, 0.21)",
      "glowB": "rgba(176, 222, 181, 0.1)",
      "top": "#160f08",
      "middle": "#2d2112",
      "bottom": "#41331c",
      "treeFilter": "sepia(0.65) hue-rotate(343deg) saturate(1.02)"
    }
  },
  {
    "id": "maple-passage",
    "minimum": 25,
    "label": "Maple Passage",
    "sigil": "楓",
    "description": "Copper leaves turn the trail into a deliberate autumn crossing.",
    "palette": {
      "accent": "#ff9677",
      "accentSoft": "#ffe0d0",
      "gold": "#ffc96d",
      "mint": "#a7dfc6",
      "moon": "#f3dfdf",
      "panel": "rgba(34, 15, 19, 0.95)",
      "line": "rgba(255, 209, 195, 0.18)",
      "glowA": "rgba(255, 121, 91, 0.2)",
      "glowB": "rgba(206, 76, 111, 0.13)",
      "top": "#190a10",
      "middle": "#321923",
      "bottom": "#42271f",
      "treeFilter": "sepia(0.52) hue-rotate(323deg) saturate(1.3)"
    }
  },
  {
    "id": "indigo-harbor",
    "minimum": 30,
    "label": "Indigo Harbor",
    "sigil": "藍",
    "description": "A cool harbor receives the rhythm and reflects it in slower waves.",
    "palette": {
      "accent": "#a9b7ff",
      "accentSoft": "#e3e8ff",
      "gold": "#cad6ff",
      "mint": "#85dfd0",
      "moon": "#dce8ff",
      "panel": "rgba(9, 12, 35, 0.95)",
      "line": "rgba(198, 210, 255, 0.18)",
      "glowA": "rgba(94, 113, 244, 0.22)",
      "glowB": "rgba(89, 208, 221, 0.11)",
      "top": "#05081a",
      "middle": "#101838",
      "bottom": "#18274c",
      "treeFilter": "grayscale(0.16) hue-rotate(38deg) saturate(0.76)"
    }
  },
  {
    "id": "silver-orchard",
    "minimum": 35,
    "label": "Silver Orchard",
    "sigil": "銀",
    "description": "Moonlit branches sharpen the contrast without losing the bloom.",
    "palette": {
      "accent": "#dce7f0",
      "accentSoft": "#ffffff",
      "gold": "#e9d7a0",
      "mint": "#a9e6d3",
      "moon": "#f1f7ff",
      "panel": "rgba(13, 18, 27, 0.95)",
      "line": "rgba(230, 240, 250, 0.19)",
      "glowA": "rgba(191, 214, 235, 0.18)",
      "glowB": "rgba(151, 225, 207, 0.1)",
      "top": "#090d14",
      "middle": "#161e2a",
      "bottom": "#28313a",
      "treeFilter": "grayscale(0.72) hue-rotate(32deg) brightness(1.12)"
    }
  },
  {
    "id": "vermilion-gate",
    "minimum": 40,
    "label": "Vermilion Gate",
    "sigil": "朱",
    "description": "A bright threshold introduces a firmer pulse and ceremonial red.",
    "palette": {
      "accent": "#ff776c",
      "accentSoft": "#ffd2c9",
      "gold": "#ffcf72",
      "mint": "#8ed9bd",
      "moon": "#f3dde3",
      "panel": "rgba(34, 9, 14, 0.95)",
      "line": "rgba(255, 190, 184, 0.19)",
      "glowA": "rgba(255, 76, 66, 0.22)",
      "glowB": "rgba(236, 153, 71, 0.12)",
      "top": "#1a060b",
      "middle": "#350f17",
      "bottom": "#48221b",
      "treeFilter": "sepia(0.48) hue-rotate(318deg) saturate(1.45)"
    }
  },
  {
    "id": "quiet-tundra",
    "minimum": 45,
    "label": "Quiet Tundra",
    "sigil": "静",
    "description": "The road widens into cold air, muted edges, and patient silence.",
    "palette": {
      "accent": "#b9dcf5",
      "accentSoft": "#eaf7ff",
      "gold": "#e5ddaa",
      "mint": "#a6e1d2",
      "moon": "#edf7ff",
      "panel": "rgba(8, 19, 28, 0.95)",
      "line": "rgba(210, 235, 250, 0.18)",
      "glowA": "rgba(123, 197, 238, 0.18)",
      "glowB": "rgba(177, 226, 220, 0.1)",
      "top": "#061019",
      "middle": "#102635",
      "bottom": "#1b3541",
      "treeFilter": "grayscale(0.38) hue-rotate(43deg) saturate(0.7) brightness(1.08)"
    }
  },
  {
    "id": "moon-garden",
    "minimum": 50,
    "label": "Moon Garden",
    "sigil": "月",
    "description": "An indigo garden slows the player just enough to hear every interval.",
    "palette": {
      "accent": "#aebcff",
      "accentSoft": "#e2e8ff",
      "gold": "#cddcff",
      "mint": "#8ed9cc",
      "moon": "#eef2ff",
      "panel": "rgba(8, 9, 31, 0.95)",
      "line": "rgba(202, 211, 255, 0.18)",
      "glowA": "rgba(87, 109, 231, 0.22)",
      "glowB": "rgba(151, 118, 223, 0.11)",
      "top": "#050619",
      "middle": "#111438",
      "bottom": "#20224b",
      "treeFilter": "grayscale(0.22) hue-rotate(48deg) saturate(0.78)"
    }
  },
  {
    "id": "copper-shrine",
    "minimum": 55,
    "label": "Copper Shrine",
    "sigil": "銅",
    "description": "Old copper and moss create a grounded pause before the higher trail.",
    "palette": {
      "accent": "#c9966a",
      "accentSoft": "#efd6b9",
      "gold": "#e3bc6b",
      "mint": "#9fd6b0",
      "moon": "#e6dfd8",
      "panel": "rgba(24, 17, 12, 0.95)",
      "line": "rgba(234, 207, 178, 0.17)",
      "glowA": "rgba(183, 117, 67, 0.19)",
      "glowB": "rgba(114, 169, 111, 0.11)",
      "top": "#120c08",
      "middle": "#281c12",
      "bottom": "#382b1d",
      "treeFilter": "sepia(0.68) hue-rotate(338deg) saturate(0.88)"
    }
  },
  {
    "id": "cobalt-torrent",
    "minimum": 60,
    "label": "Cobalt Torrent",
    "sigil": "蒼",
    "description": "Blue current drives a more restless movement through the same calm form.",
    "palette": {
      "accent": "#76a8ff",
      "accentSoft": "#d6e4ff",
      "gold": "#b8d8ff",
      "mint": "#7fe1d6",
      "moon": "#dfeaff",
      "panel": "rgba(5, 13, 36, 0.95)",
      "line": "rgba(176, 202, 255, 0.18)",
      "glowA": "rgba(49, 103, 237, 0.24)",
      "glowB": "rgba(62, 206, 203, 0.12)",
      "top": "#03091c",
      "middle": "#0b1b42",
      "bottom": "#153260",
      "treeFilter": "grayscale(0.12) hue-rotate(41deg) saturate(0.96)"
    }
  },
  {
    "id": "jade-horizon",
    "minimum": 65,
    "label": "Jade Horizon",
    "sigil": "翠",
    "description": "A long jade line makes every exact landing feel newly visible.",
    "palette": {
      "accent": "#82d7b6",
      "accentSoft": "#dcf7eb",
      "gold": "#d8dc8b",
      "mint": "#8ce4cd",
      "moon": "#e2f6ef",
      "panel": "rgba(7, 27, 23, 0.95)",
      "line": "rgba(190, 239, 220, 0.18)",
      "glowA": "rgba(54, 184, 137, 0.21)",
      "glowB": "rgba(187, 215, 88, 0.1)",
      "top": "#041510",
      "middle": "#0d2d24",
      "bottom": "#194438",
      "treeFilter": "sepia(0.1) hue-rotate(88deg) saturate(1.1)"
    }
  },
  {
    "id": "saffron-hollow",
    "minimum": 70,
    "label": "Saffron Hollow",
    "sigil": "黄",
    "description": "A bright hollow turns restraint into warmth without blinding the page.",
    "palette": {
      "accent": "#e9c56d",
      "accentSoft": "#fff0bd",
      "gold": "#ffd46d",
      "mint": "#9bdac2",
      "moon": "#f4ead3",
      "panel": "rgba(31, 24, 8, 0.95)",
      "line": "rgba(244, 225, 171, 0.18)",
      "glowA": "rgba(221, 169, 50, 0.21)",
      "glowB": "rgba(136, 211, 176, 0.1)",
      "top": "#171103",
      "middle": "#30260b",
      "bottom": "#453719",
      "treeFilter": "sepia(0.72) hue-rotate(356deg) saturate(1.06)"
    }
  },
  {
    "id": "violet-summit",
    "minimum": 75,
    "label": "Violet Summit",
    "sigil": "紫",
    "description": "The summit brings high violet air and a melody with wider intervals.",
    "palette": {
      "accent": "#c29cff",
      "accentSoft": "#eadcff",
      "gold": "#dfc5ff",
      "mint": "#9fded0",
      "moon": "#eee5ff",
      "panel": "rgba(20, 8, 37, 0.95)",
      "line": "rgba(222, 194, 255, 0.18)",
      "glowA": "rgba(147, 82, 245, 0.22)",
      "glowB": "rgba(104, 216, 204, 0.11)",
      "top": "#0d041b",
      "middle": "#21103c",
      "bottom": "#352255",
      "treeFilter": "grayscale(0.08) hue-rotate(286deg) saturate(1.14)"
    }
  },
  {
    "id": "frost-pavilion",
    "minimum": 80,
    "label": "Frost Pavilion",
    "sigil": "霜",
    "description": "Glass-cold harmonics and soft frost make the eighth movement spacious.",
    "palette": {
      "accent": "#bceaff",
      "accentSoft": "#ecfaff",
      "gold": "#d7eaff",
      "mint": "#9ee2d6",
      "moon": "#f4fbff",
      "panel": "rgba(7, 20, 31, 0.95)",
      "line": "rgba(210, 239, 255, 0.18)",
      "glowA": "rgba(119, 212, 250, 0.2)",
      "glowB": "rgba(179, 232, 226, 0.1)",
      "top": "#05121b",
      "middle": "#102a3a",
      "bottom": "#1d4050",
      "treeFilter": "grayscale(0.46) hue-rotate(38deg) saturate(0.68) brightness(1.13)"
    }
  },
  {
    "id": "crimson-current",
    "minimum": 85,
    "label": "Crimson Current",
    "sigil": "紅",
    "description": "A dark red current adds tension while the underlying grammar stays exact.",
    "palette": {
      "accent": "#ff667d",
      "accentSoft": "#ffcbd3",
      "gold": "#f1bd70",
      "mint": "#8ad6bf",
      "moon": "#ead9df",
      "panel": "rgba(37, 7, 17, 0.95)",
      "line": "rgba(255, 178, 193, 0.18)",
      "glowA": "rgba(239, 48, 81, 0.23)",
      "glowB": "rgba(178, 62, 113, 0.13)",
      "top": "#1b030b",
      "middle": "#360a18",
      "bottom": "#4d1721",
      "treeFilter": "sepia(0.32) hue-rotate(307deg) saturate(1.52)"
    }
  },
  {
    "id": "obsidian-bloom",
    "minimum": 90,
    "label": "Obsidian Bloom",
    "sigil": "黒",
    "description": "Nearly black petals retain a narrow line of living color.",
    "palette": {
      "accent": "#d794d9",
      "accentSoft": "#f1d9f2",
      "gold": "#d7b86c",
      "mint": "#86cbb4",
      "moon": "#dddce7",
      "panel": "rgba(9, 7, 13, 0.97)",
      "line": "rgba(214, 183, 218, 0.15)",
      "glowA": "rgba(137, 71, 142, 0.2)",
      "glowB": "rgba(83, 163, 139, 0.09)",
      "top": "#050306",
      "middle": "#100b12",
      "bottom": "#211622",
      "treeFilter": "grayscale(0.72) hue-rotate(281deg) saturate(0.72)"
    }
  },
  {
    "id": "ashen-crown",
    "minimum": 95,
    "label": "Ashen Crown",
    "sigil": "灰",
    "description": "Color drains toward the crossing; only the crown keeps a warm edge.",
    "palette": {
      "accent": "#c7c1bd",
      "accentSoft": "#ebe6e2",
      "gold": "#c9ad6d",
      "mint": "#9fc5b4",
      "moon": "#dfdfe3",
      "panel": "rgba(13, 12, 13, 0.97)",
      "line": "rgba(219, 214, 208, 0.15)",
      "glowA": "rgba(149, 142, 137, 0.17)",
      "glowB": "rgba(184, 145, 77, 0.08)",
      "top": "#080708",
      "middle": "#171516",
      "bottom": "#292524",
      "treeFilter": "grayscale(0.88) sepia(0.08) brightness(0.93)"
    }
  },
  {
    "id": "dark-crossing",
    "minimum": 100,
    "label": "Dark Crossing",
    "sigil": "闇",
    "description": "The trail reaches grayscale, the harmony turns ominous, and the road continues.",
    "palette": {
      "accent": "#aaaeb6",
      "accentSoft": "#e1e3e8",
      "gold": "#baa56f",
      "mint": "#8ea99f",
      "moon": "#d8dbe0",
      "panel": "rgba(5, 6, 8, 0.98)",
      "line": "rgba(190, 195, 205, 0.14)",
      "glowA": "rgba(103, 108, 119, 0.17)",
      "glowB": "rgba(142, 123, 83, 0.07)",
      "top": "#020304",
      "middle": "#090b0e",
      "bottom": "#15171b",
      "treeFilter": "grayscale(1) contrast(1.15) brightness(0.72)"
    }
  }
];
const prefixes = [
  "Silent",
  "Solar",
  "Verdant",
  "Frosted",
  "Obsidian",
  "Velvet",
  "Cobalt",
  "Golden",
  "Lunar",
  "Scarlet",
  "Glass",
  "Distant",
  "Cedar",
  "Ivory",
  "Ember",
  "Hidden",
  "Radiant",
  "Dusky",
  "Astral",
  "Wild"
];
const suffixes = [
  "Passage",
  "Forest",
  "Harbor",
  "Garden",
  "Horizon",
  "Archive",
  "Sanctum",
  "Crossing",
  "Orchard",
  "Summit",
  "Torrent",
  "Lantern",
  "Threshold",
  "Grove",
  "Trail",
  "Valley",
  "Pavilion",
  "Current",
  "Shrine",
  "Steppe",
  "Crown"
];

export const WORLD_INTERVAL = 5;
export const AUTHORED_WORLDS = Object.freeze(
  authored.map((entry) => Object.freeze({
    ...entry,
    palette: Object.freeze(entry.palette)
  }))
);

const normalizeCount = (value) =>
  Math.max(0, Math.floor(Number(value) || 0));

function proceduralWorld(correct) {
  const worldIndex = Math.floor(normalizeCount(correct) / WORLD_INTERVAL);
  const proceduralIndex = Math.max(0, worldIndex - AUTHORED_WORLDS.length);
  const prefix = prefixes[proceduralIndex % prefixes.length];
  const suffix = suffixes[
    (proceduralIndex * 11 + Math.floor(proceduralIndex / 7) * 5 + 1)
      % suffixes.length
  ];
  const hue = (proceduralIndex * 137.508 + 208) % 360;
  const companion = (hue + 58) % 360;
  const warm = (hue + 122) % 360;

  return Object.freeze({
    id: `endless-${worldIndex}`,
    minimum: worldIndex * WORLD_INTERVAL,
    label: `${prefix} ${suffix}`,
    sigil: "∞",
    description:
      "An endless, deterministic world generated from the road already traveled.",
    palette: Object.freeze({
      accent: `hsl(${hue} 82% 72%)`,
      accentSoft: `hsl(${hue} 78% 89%)`,
      gold: `hsl(${warm} 72% 72%)`,
      mint: `hsl(${companion} 66% 72%)`,
      moon: `hsl(${(hue + 24) % 360} 48% 88%)`,
      panel: `hsla(${hue} 38% 8% / 0.96)`,
      line: `hsla(${hue} 65% 88% / 0.17)`,
      glowA: `hsla(${hue} 78% 62% / 0.20)`,
      glowB: `hsla(${companion} 66% 58% / 0.11)`,
      top: `hsl(${hue} 48% 5%)`,
      middle: `hsl(${hue} 42% 12%)`,
      bottom: `hsl(${companion} 36% 18%)`,
      treeFilter:
        `grayscale(0.18) hue-rotate(${Math.round(hue - 330)}deg) ` +
        "saturate(0.92) contrast(1.08)"
    })
  });
}

export function worldForCount(correct) {
  const count = normalizeCount(correct);
  for (let index = AUTHORED_WORLDS.length - 1; index >= 0; index -= 1) {
    if (count >= AUTHORED_WORLDS[index].minimum) {
      if (index === AUTHORED_WORLDS.length - 1 && count >= 105) {
        return proceduralWorld(count);
      }
      return AUTHORED_WORLDS[index];
    }
  }
  return AUTHORED_WORLDS[0];
}

export function nextWorldForCount(correct) {
  const count = normalizeCount(correct);
  const minimum = (Math.floor(count / WORLD_INTERVAL) + 1) * WORLD_INTERVAL;
  return worldForCount(minimum);
}

export function applyWorldPalette(target, world) {
  const palette = world.palette;
  const values = {
    "--ck-sakura": palette.accent,
    "--ck-sakura-soft": palette.accentSoft,
    "--ck-gold": palette.gold,
    "--ck-mint": palette.mint,
    "--ck-moon": palette.moon,
    "--ck-panel": palette.panel,
    "--ck-line": palette.line,
    "--ck-world-glow-a": palette.glowA,
    "--ck-world-glow-b": palette.glowB,
    "--ck-world-top": palette.top,
    "--ck-world-middle": palette.middle,
    "--ck-world-bottom": palette.bottom,
    "--ck-tree-filter": palette.treeFilter
  };
  for (const [name, value] of Object.entries(values)) {
    target.style.setProperty(name, value);
  }
}
